# Generated by Django 5.2.3 on 2025-10-18 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.TextField()),
                ('color', models.CharField(blank=True, default='', max_length=32)),
            ],
            options={
                'verbose_name': 'Тип контейнера',
                'verbose_name_plural': 'Типы контейнеров',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.TextField()),
                ('duration', models.CharField(blank=True, default='', max_length=64)),
                ('category_code', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'verbose_name': 'Панель',
                'verbose_name_plural': 'Панели',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Biomaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.TextField()),
                ('barcodeinfo', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Биоматериал',
                'verbose_name_plural': 'Биоматериалы',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='lab_biomate_code_e0afc8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=32)),
                ('patient_fio', models.TextField(blank=True, default='')),
                ('patient_birthdate', models.DateField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Заявка (направление)',
                'verbose_name_plural': 'Заявки (направления)',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['number'], name='lab_order_number_baf49a_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='', max_length=32)),
                ('released_doctor', models.TextField(blank=True, default='')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='lab.order')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lab.panel')),
            ],
            options={
                'verbose_name': 'Панель в заявке',
                'verbose_name_plural': 'Панели в заявках',
                'unique_together': {('order', 'panel')},
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.TextField()),
                ('unit', models.CharField(blank=True, default='', max_length=128)),
                ('method', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('low', models.CharField(blank=True, default='', max_length=64)),
                ('high', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='lab_test_code_cd8c2e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Analyte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('name', models.TextField()),
                ('unit', models.CharField(blank=True, default='', max_length=64)),
                ('norm_low', models.CharField(blank=True, default='', max_length=64)),
                ('norm_high', models.CharField(blank=True, default='', max_length=64)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytes', to='lab.test')),
            ],
            options={
                'verbose_name': 'Аналит',
                'verbose_name_plural': 'Аналиты',
                'ordering': ['test_id', 'code'],
            },
        ),
        migrations.CreateModel(
            name='TestRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_code', models.CharField(db_index=True, max_length=64)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, default='')),
                ('dependent_tests', models.ManyToManyField(blank=True, related_name='required_fields', to='lab.test')),
            ],
            options={
                'verbose_name': 'Требование к тесту',
                'verbose_name_plural': 'Требования к тестам',
                'ordering': ['field_code'],
            },
        ),
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=128)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizations', to='lab.panel')),
            ],
            options={
                'verbose_name': 'Локализация панели',
                'verbose_name_plural': 'Локализации панелей',
                'unique_together': {('panel', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='PanelLinked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_parents', to='lab.panel')),
                ('main_panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_children', to='lab.panel')),
            ],
            options={
                'verbose_name': 'Связанная панель',
                'verbose_name_plural': 'Связанные панели',
                'unique_together': {('main_panel', 'extra_panel')},
            },
        ),
        migrations.CreateModel(
            name='PanelMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biomaterial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lab.biomaterial')),
                ('container_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lab.containertype')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel_materials', to='lab.panel')),
            ],
            options={
                'verbose_name': 'Материал панели',
                'verbose_name_plural': 'Материалы панелей',
                'unique_together': {('panel', 'biomaterial', 'container_type')},
            },
        ),
        migrations.CreateModel(
            name='ResultEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, default='')),
                ('unit', models.CharField(blank=True, default='', max_length=64)),
                ('norm_low', models.CharField(blank=True, default='', max_length=64)),
                ('norm_high', models.CharField(blank=True, default='', max_length=64)),
                ('comment', models.TextField(blank=True, default='')),
                ('rawresult', models.TextField(blank=True, default='')),
                ('released_doctor', models.TextField(blank=True, default='')),
                ('analyte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.analyte')),
                ('order_panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='lab.orderpanel')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lab.test')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
                'ordering': ['order_panel_id', 'test_id'],
                'indexes': [models.Index(fields=['order_panel', 'test'], name='lab_resulte_order_p_e08224_idx')],
            },
        ),
        migrations.CreateModel(
            name='PanelTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel_tests', to='lab.panel')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lab.test')),
            ],
            options={
                'verbose_name': 'Тест панели',
                'verbose_name_plural': 'Тесты панелей',
                'indexes': [models.Index(fields=['panel', 'test'], name='lab_panelte_panel_i_115284_idx')],
                'unique_together': {('panel', 'test')},
            },
        ),
        migrations.AddIndex(
            model_name='analyte',
            index=models.Index(fields=['code'], name='lab_analyte_code_27b73d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='analyte',
            unique_together={('test', 'code')},
        ),
    ]
