# Generated by Django 5.2.3 on 2025-10-19 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.TextField()),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='RUB', max_length=8)),
                ('duration', models.CharField(blank=True, default='', max_length=64)),
                ('comment', models.TextField(blank=True, default='')),
                ('panel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='lab.panel')),
            ],
            options={
                'verbose_name': 'Услуга (прайс)',
                'verbose_name_plural': 'Прайс-лист',
                'ordering': ['code'],
            },
        ),
    ]
