# Generated by Django 5.2.3 on 2025-10-21 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='category_code',
            field=models.CharField(blank=True, default='', help_text='Легаси. Не использовать напрямую.', max_length=64),
        ),
        migrations.CreateModel(
            name='PanelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.TextField()),
                ('sorter', models.IntegerField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='lab.panelcategory')),
            ],
            options={
                'verbose_name': 'Категория панели',
                'verbose_name_plural': 'Категории панелей',
                'ordering': ['sorter', 'code'],
            },
        ),
        migrations.AddField(
            model_name='panel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panels', to='lab.panelcategory'),
        ),
        migrations.AddIndex(
            model_name='panelcategory',
            index=models.Index(fields=['code'], name='lab_panelca_code_de0fd3_idx'),
        ),
        migrations.AddIndex(
            model_name='panelcategory',
            index=models.Index(fields=['parent', 'sorter'], name='lab_panelca_parent__0c9e43_idx'),
        ),
    ]
