# Generated by Django 5.2.3 on 2025-10-30 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_alter_panel_category_code_panelcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelPreanalytic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training', models.TextField(blank=True, default='', help_text='Подготовка к исследованию')),
                ('centrifugation', models.TextField(blank=True, default='', help_text='Центрифугирование')),
                ('storage_transportation', models.TextField(blank=True, default='', help_text='Хранение и транспортировка')),
                ('note', models.TextField(blank=True, default='', help_text='Примечание')),
                ('min_count', models.CharField(blank=True, default='', help_text="Минимальный объем образца (например, '2 мл.')", max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('panel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preanalytic', to='lab.panel')),
            ],
            options={
                'verbose_name': 'Преаналитика панели',
                'verbose_name_plural': 'Преаналитика панелей',
                'indexes': [models.Index(fields=['panel'], name='lab_panelpr_panel_i_b3d818_idx')],
            },
        ),
    ]
