# Generated by Django 5.2.3 on 2025-10-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_panelpreanalytic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelpreanalytic',
            name='min_count',
            field=models.TextField(blank=True, default='', help_text='Минимальный объем образца'),
        ),
    ]
