# Generated by Django 5.2.3 on 2025-09-24 12:07

import django_ckeditor_5.fields
import main.fields
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Текст')),
                ('photo', main.fields.WEBPField(blank=True, null=True, upload_to=main.models.image_folder, verbose_name='фото 633x550px')),
                ('content2', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Текст2')),
                ('photo2', main.fields.WEBPField(blank=True, null=True, upload_to=main.models.image_folder, verbose_name='фото2')),
                ('photo3', main.fields.WEBPField(blank=True, null=True, upload_to=main.models.image_folder, verbose_name='Фото№3')),
                ('content3', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Текст3')),
                ('photo4', main.fields.WEBPField(blank=True, null=True, upload_to=main.models.image_folder, verbose_name='Фото№4')),
                ('photo5', main.fields.WEBPField(blank=True, null=True, upload_to=main.models.image_folder, verbose_name='Фото№5')),
                ('content4', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Текст4')),
                ('time_create', models.DateTimeField(verbose_name='Дата и время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['time_create', 'title'],
            },
        ),
    ]
