# Generated by Django 5.2.3 on 2025-10-13 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_categorylecture_categorynews_categoryprog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название материала')),
                ('normalized_name', models.CharField(blank=True, help_text='Lower-cased/trimmed variant for search', max_length=255, verbose_name='Нормализованное имя')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'indexes': [models.Index(fields=['normalized_name'], name='main_materi_normali_a7ef9d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Слаг')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='main.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория анализа',
                'verbose_name_plural': 'Категории анализов',
                'indexes': [models.Index(fields=['slug'], name='main_catego_slug_f935f9_idx')],
            },
        ),
    ]
