# Generated by Django 5.2.3 on 2025-10-14 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_material_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Код исследования из источника (например, '10.001').", max_length=32, unique=True, verbose_name='Код исследования')),
                ('name', models.TextField(verbose_name='Наименование исследования')),
                ('result_kind', models.CharField(choices=[('qual', 'Качественный'), ('quant', 'Количественный'), ('mixed', 'Смешанный'), ('concl', 'Заключение'), ('complex', 'Комплексный'), ('other', 'Другое/иное')], default='other', max_length=16, verbose_name='Тип результата')),
                ('result_kind_raw', models.CharField(blank=True, help_text='Исходная строка из источника', max_length=128, verbose_name='Исходное значение типа результата')),
                ('turnaround_days', models.PositiveSmallIntegerField(blank=True, help_text='Срок в рабочих днях (число)', null=True, verbose_name='Срок выполнения (дни)')),
                ('turnaround_note', models.CharField(blank=True, help_text="Сохранённое примечание из колонки (например, '3*')", max_length=32, verbose_name='Примечание к сроку')),
                ('urgent_available', models.BooleanField(blank=True, help_text='Возможность срочного выполнения', null=True, verbose_name='Срочное выполнение')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('currency', models.CharField(default='RUB', max_length=8, verbose_name='Валюта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('preparation', models.TextField(blank=True, verbose_name='Подготовка')),
                ('clinical_info', models.TextField(blank=True, verbose_name='Клиническая информация')),
                ('interpretation', models.TextField(blank=True, verbose_name='Интерпретация результатов')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Слаг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='main.category', verbose_name='Категория')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='main.material', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Анализ',
                'verbose_name_plural': 'Анализы',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['slug'], name='main_analis_slug_b113b9_idx'), models.Index(fields=['code'], name='main_analis_code_81c405_idx'), models.Index(fields=['price'], name='main_analis_price_8cef18_idx')],
            },
        ),
    ]
