# Generated by Django 5.2.3 on 2025-10-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_analise'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='full_name',
            field=models.TextField(default=0, verbose_name='Полное название категории'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name_hash',
            field=models.CharField(default=0, max_length=64, unique=True, verbose_name='Хеш полного названия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='full_name',
            field=models.TextField(default=0, verbose_name='Полное название материала'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='name_hash',
            field=models.CharField(default=0, max_length=64, unique=True, verbose_name='Хеш полного названия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Короткое название категории'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Короткое название материала'),
        ),
        migrations.AlterField(
            model_name='material',
            name='normalized_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Нормализованное имя'),
        ),
    ]
