# Generated by Django 5.2.3 on 2025-10-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_backfill_material_category_hashes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='full_name',
            field=models.TextField(blank=True, verbose_name='Полное название материала'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название материала'),
        ),
        migrations.DeleteModel(
            name='Analise',
        ),
    ]
