# Generated by Django 5.2.3 on 2025-10-17 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_material_full_name_alter_material_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
