# Generated by Django 5.2.3 on 2025-10-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_biomaterial_containertype_labcategory_labpanel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labpanel',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='name',
            field=models.TextField(),
        ),
    ]
