# Generated by Django 5.2.3 on 2025-10-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_labpanel_name_alter_labtest_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biomaterial',
            options={'ordering': ['name'], 'verbose_name': 'Биоматериал', 'verbose_name_plural': 'Биоматериалы'},
        ),
        migrations.AlterModelOptions(
            name='containertype',
            options={'ordering': ['name'], 'verbose_name': 'Тип контейнера', 'verbose_name_plural': 'Типы контейнеров'},
        ),
        migrations.AlterModelOptions(
            name='labcategory',
            options={'ordering': ['name'], 'verbose_name': 'Категория анализа', 'verbose_name_plural': 'Категории анализов'},
        ),
        migrations.AlterModelOptions(
            name='labpanel',
            options={'ordering': ['name'], 'verbose_name': 'Панель', 'verbose_name_plural': 'Панели'},
        ),
        migrations.AlterModelOptions(
            name='labtest',
            options={'ordering': ['name'], 'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AlterModelOptions(
            name='panelcategory',
            options={'verbose_name': 'Категория панели', 'verbose_name_plural': 'Категории панелей'},
        ),
        migrations.AlterModelOptions(
            name='panelitem',
            options={'verbose_name': 'Элемент панели (тест)', 'verbose_name_plural': 'Состав панелей'},
        ),
        migrations.AlterModelOptions(
            name='preanalytic',
            options={'verbose_name': 'Преаналитика', 'verbose_name_plural': 'Преаналитика'},
        ),
        migrations.AlterModelOptions(
            name='syncstamp',
            options={'verbose_name': 'Отметка синка', 'verbose_name_plural': 'Отметки синка'},
        ),
        migrations.AlterModelOptions(
            name='testcategory',
            options={'verbose_name': 'Категория теста', 'verbose_name_plural': 'Категории тестов'},
        ),
        migrations.AlterModelOptions(
            name='testrequirement',
            options={'verbose_name': 'Требование к тесту', 'verbose_name_plural': 'Требования к тестам'},
        ),
        migrations.AddField(
            model_name='biomaterial',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='biomaterial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='containertype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='containertype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='labcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='labcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='labpanel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='labpanel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='biomaterial',
            name='external_id',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='biomaterial',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='external_id',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='labcategory',
            name='external_id',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='labcategory',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='labcategory',
            name='parent_external_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='labpanel',
            name='code',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='labpanel',
            name='external_id',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='code',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='external_id',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='short_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='preanalytic',
            name='target_external_id',
            field=models.CharField(max_length=128),
        ),
        migrations.AddIndex(
            model_name='labcategory',
            index=models.Index(fields=['parent_external_id'], name='main_labcat_parent__89a581_idx'),
        ),
        migrations.AddIndex(
            model_name='labcategory',
            index=models.Index(fields=['is_active'], name='main_labcat_is_acti_f993dd_idx'),
        ),
        migrations.AddIndex(
            model_name='labpanel',
            index=models.Index(fields=['is_active'], name='main_labpan_is_acti_d90df6_idx'),
        ),
        migrations.AddIndex(
            model_name='labpanel',
            index=models.Index(fields=['updated_at'], name='main_labpan_updated_2b2c67_idx'),
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['is_active'], name='main_labtes_is_acti_ba4e0f_idx'),
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['updated_at'], name='main_labtes_updated_7b9f1a_idx'),
        ),
        migrations.AddIndex(
            model_name='preanalytic',
            index=models.Index(fields=['target_type', 'target_external_id'], name='main_preana_target__470a58_idx'),
        ),
    ]
