# Generated by Django 5.2.3 on 2025-10-18 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_biomaterial_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labcategory',
            options={'ordering': ['name'], 'verbose_name': 'Категория панели', 'verbose_name_plural': 'Категории панелей'},
        ),
        migrations.AlterModelOptions(
            name='panelitem',
            options={'verbose_name': 'Состав панели', 'verbose_name_plural': 'Составы панелей'},
        ),
        migrations.AlterModelOptions(
            name='syncstamp',
            options={'verbose_name': 'Метка синхронизации', 'verbose_name_plural': 'Метки синхронизации'},
        ),
        migrations.AlterModelOptions(
            name='testrequirement',
            options={'ordering': ('-is_active', 'id'), 'verbose_name': 'Требование теста', 'verbose_name_plural': 'Требования тестов'},
        ),
        migrations.RemoveIndex(
            model_name='labcategory',
            name='main_labcat_parent__89a581_idx',
        ),
        migrations.RemoveIndex(
            model_name='labcategory',
            name='main_labcat_is_acti_f993dd_idx',
        ),
        migrations.RemoveIndex(
            model_name='labpanel',
            name='main_labpan_is_acti_d90df6_idx',
        ),
        migrations.RemoveIndex(
            model_name='labpanel',
            name='main_labpan_updated_2b2c67_idx',
        ),
        migrations.RemoveIndex(
            model_name='labtest',
            name='main_labtes_is_acti_ba4e0f_idx',
        ),
        migrations.RemoveIndex(
            model_name='labtest',
            name='main_labtes_updated_7b9f1a_idx',
        ),
        migrations.RemoveIndex(
            model_name='preanalytic',
            name='main_preana_target__470a58_idx',
        ),
        migrations.AlterField(
            model_name='syncstamp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at'),
        ),
        migrations.RenameField(
            model_name='syncstamp',
            old_name='updated_at',
            new_name='time',
        ),
        migrations.AddField(
            model_name='testrequirement',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='testrequirement',
            name='name',
            field=models.CharField(default=0, max_length=255, verbose_name='Требование'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testrequirement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AddField(
            model_name='testrequirement',
            name='value',
            field=models.CharField(blank=True, max_length=255, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='biomaterial',
            name='external_id',
            field=models.CharField(max_length=128, unique=True, verbose_name='Внешний ID'),
        ),
        migrations.AlterField(
            model_name='biomaterial',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='biomaterial',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='biomaterial',
            name='raw_xml',
            field=models.TextField(blank=True, null=True, verbose_name='Сырой XML'),
        ),
        migrations.AlterField(
            model_name='biomaterial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='external_id',
            field=models.CharField(max_length=128, unique=True, verbose_name='Внешний ID'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='raw_xml',
            field=models.TextField(blank=True, null=True, verbose_name='Сырой XML'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='labcategory',
            name='external_id',
            field=models.CharField(max_length=128, unique=True, verbose_name='Внешний ID'),
        ),
        migrations.AlterField(
            model_name='labcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='labcategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='labcategory',
            name='parent_external_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Родительский ID'),
        ),
        migrations.AlterField(
            model_name='labcategory',
            name='raw_xml',
            field=models.TextField(blank=True, null=True, verbose_name='Сырой XML'),
        ),
        migrations.AlterField(
            model_name='labcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='labpanel',
            name='code',
            field=models.CharField(max_length=128, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='labpanel',
            name='external_id',
            field=models.CharField(max_length=128, unique=True, verbose_name='Внешний ID'),
        ),
        migrations.AlterField(
            model_name='labpanel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='labpanel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='labpanel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='labpanel',
            name='raw_xml',
            field=models.TextField(blank=True, null=True, verbose_name='Сырой XML'),
        ),
        migrations.AlterField(
            model_name='labpanel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='biomaterial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.biomaterial', verbose_name='Биоматериал'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='code',
            field=models.CharField(max_length=128, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='container_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.containertype', verbose_name='Тип контейнера'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='external_id',
            field=models.CharField(max_length=128, unique=True, verbose_name='Внешний ID'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='raw_xml',
            field=models.TextField(blank=True, null=True, verbose_name='Сырой XML'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Короткое имя'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='panelcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.labcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='panelcategory',
            name='panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.labpanel', verbose_name='Панель'),
        ),
        migrations.AlterField(
            model_name='panelitem',
            name='panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.labpanel', verbose_name='Панель'),
        ),
        migrations.AlterField(
            model_name='panelitem',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.labtest', verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='preanalytic',
            name='raw_xml',
            field=models.TextField(blank=True, null=True, verbose_name='Сырой XML'),
        ),
        migrations.AlterField(
            model_name='preanalytic',
            name='target_external_id',
            field=models.CharField(max_length=128, verbose_name='Внешний ID объекта'),
        ),
        migrations.AlterField(
            model_name='preanalytic',
            name='target_type',
            field=models.CharField(max_length=50, verbose_name='Тип объекта'),
        ),
        migrations.AlterField(
            model_name='syncstamp',
            name='catalog',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='testcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.labcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='testcategory',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.labtest', verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='testrequirement',
            name='raw_xml',
            field=models.TextField(blank=True, null=True, verbose_name='Сырой XML'),
        ),
        migrations.AlterField(
            model_name='testrequirement',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.labtest', verbose_name='Тест'),
        ),
    ]
