# Generated by Django 5.2.3 on 2025-10-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_labcategory_options_alter_panelitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labpanel',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
    ]
