# Generated by Django 5.2.3 on 2025-10-18 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_labpanel_name'),
    ]

    operations = [
        # 1) Сначала удаляем зависимые таблицы (ссылаются на тесты/панели/категории)
        migrations.DeleteModel(
            name='PanelItem',
        ),
        migrations.DeleteModel(
            name='TestCategory',
        ),
        migrations.DeleteModel(
            name='TestRequirement',
        ),

        # 2) Теперь можно удалить связывающую таблицу категорий панелей
        migrations.DeleteModel(
            name='PanelCategory',
        ),

        # 3) Удаляем сами панели/тесты и справочники
        migrations.DeleteModel(
            name='LabPanel',
        ),
        migrations.DeleteModel(
            name='LabTest',
        ),
        migrations.DeleteModel(
            name='LabCategory',
        ),
        migrations.DeleteModel(
            name='Biomaterial',
        ),
        migrations.DeleteModel(
            name='ContainerType',
        ),

        # 4) Прочие сущности «в довесок»
        migrations.DeleteModel(
            name='Preanalytic',
        ),
        migrations.DeleteModel(
            name='SyncStamp',
        ),
    ]
