# Generated by Django 5.2.3 on 2025-10-24 21:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_labtest_biomaterial_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contact_set', to='users.location', verbose_name='Местоположение'),
        ),
        migrations.CreateModel(
            name='BusinessHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='День недели')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='Открытие')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='Закрытие')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Выходной день')),
                ('note', models.CharField(blank=True, max_length=120, verbose_name='Примечание')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='main.contact', verbose_name='Контакт')),
            ],
            options={
                'verbose_name': 'Часы работы (неделя)',
                'verbose_name_plural': 'Часы работы (неделя)',
                'ordering': ['contact', 'weekday'],
                'unique_together': {('contact', 'weekday')},
            },
        ),
        migrations.CreateModel(
            name='BusinessHourOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='Открытие')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='Закрытие')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Закрыто весь день')),
                ('note', models.CharField(blank=True, max_length=120, verbose_name='Примечание')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hour_overrides', to='main.contact', verbose_name='Контакт')),
            ],
            options={
                'verbose_name': 'Исключение часов работы',
                'verbose_name_plural': 'Исключения часов работы',
                'ordering': ['contact', 'date'],
                'unique_together': {('contact', 'date')},
            },
        ),
    ]
