# Generated by Django 5.2.3 on 2025-10-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_contact_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='booking_enabled',
            field=models.BooleanField(default=True, verbose_name='Запись включена'),
        ),
        migrations.AddField(
            model_name='contact',
            name='booking_slot_minutes',
            field=models.PositiveIntegerField(default=20, verbose_name='Длина слота, мин'),
        ),
    ]
