# Generated by Django 5.2.3 on 2025-12-10 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ('created_at',), 'verbose_name': 'Сообщение чата', 'verbose_name_plural': 'Сообщения чата'},
        ),
        migrations.AlterModelOptions(
            name='chatthread',
            options={'ordering': ('-created_at',), 'verbose_name': 'Чат-сессия', 'verbose_name_plural': 'Чат-сессии'},
        ),
    ]
