# Generated by Django 5.2.3 on 2025-12-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatmessage_options_alter_chatthread_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='vk_message_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
