# Generated by Django 5.2.3 on 2025-12-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatmessage_vk_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='vk_from_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='vk_peer_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
