# Generated by Django 5.2.3 on 2025-12-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatthread_vk_from_id_chatthread_vk_peer_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ('id',), 'verbose_name': 'Сообщение чата', 'verbose_name_plural': 'Сообщения чата'},
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(choices=[('visitor', 'Visitor'), ('operator', 'Operator'), ('system', 'System')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='vk_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['thread', 'id'], name='chatmsg_thread_id_idx'),
        ),
    ]
