# Generated by Django 5.2.3 on 2025-12-16 20:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('query', models.CharField(max_length=512)),
                ('normalized', models.CharField(blank=True, default='', max_length=512)),
                ('intents', models.JSONField(blank=True, default=list)),
                ('results', models.JSONField(blank=True, default=list)),
                ('clicked', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('panel', 'Panel'), ('test', 'Test'), ('lab_service', 'Lab Service'), ('doc', 'Document'), ('news', 'News'), ('contact', 'Contact'), ('site_service', 'Site Service')], db_index=True, max_length=32)),
                ('object_id', models.PositiveBigIntegerField(db_index=True)),
                ('title', models.CharField(max_length=512)),
                ('url', models.CharField(max_length=1024)),
                ('search_text', models.TextField()),
                ('boost', models.FloatField(default=1.0)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['kind', 'object_id'], name='assistant_s_kind_345efd_idx')],
                'unique_together': {('kind', 'object_id')},
            },
        ),
    ]
