# Generated by Django 5.2.3 on 2025-12-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_fulltext'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchindex',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
